# Generated by Django 5.2.3 on 2025-07-31 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_master_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('ai_moderating', 'На модерации'), ('ai_approved', 'Одобрен'), ('ai_rejected', 'Отклонен'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.master', verbose_name='Мастер'),
        ),
    ]
